export const tasks = [
  // Bewegung
  "Mach 5 Kniebeugen",
  "Mach 10 Kniebeugen",
  "Mach 15 Kniebeugen",
  "Mach 5 Hampelmänner",
  "Mach 10 Hampelmänner",
  "Mach 15 Hampelmänner",
  "Hüpfe 10-mal auf der Stelle",
  "Hüpfe 20-mal auf der Stelle",
  "Laufe einmal durch den Raum",
  "Laufe zweimal durch den Raum",
  "Gehe einmal rückwärts durch den Raum",
  "Gehe auf Zehenspitzen durch den Raum",
  "Gehe auf den Fersen durch den Raum",
  "Laufe im Kreis",
  "Dreh dich 3-mal im Kreis",
  "Dreh dich 5-mal im Kreis",
  "Steh 10 Sekunden auf einem Bein",
  "Steh 20 Sekunden auf einem Bein",
  "Wechsle nach 5 Sekunden das Bein",
  "Berühre den Boden",
  "Berühre die Wand",
  "Berühre eine Tür",
  "Berühre deinen Kopf mit beiden Händen",
  "Berühre deine Knie",
  "Streck beide Arme nach oben",
  "Streck beide Arme zur Seite",
  "Mach dich so groß wie möglich",
  "Mach dich so klein wie möglich",
  "Streck dich einmal richtig",
  "Schüttel beide Arme aus",
  "Schüttel beide Beine aus",
  "Spring einmal so hoch du kannst",
  "Mach einen kleinen Freudentanz",
  "Laufe 5 Sekunden auf der Stelle",
  "Bewege dich 10 Sekunden wie ein Roboter",
  "Bewege dich 10 Sekunden in Zeitlupe",
  "Laufe wie ein Pinguin",
  "Laufe wie ein Roboter",
  "Laufe wie ein Dinosaurier",
  "Laufe wie ein Cowboy",
  "Laufe wie ein Superheld",
  "Schleiche einmal durch den Raum",
  "Marschier einmal durch den Raum",
  "Mach eine Siegerpose",
  "Mach eine dramatische Pose",
  "Mach eine Statue für 10 Sekunden",
  "Mach eine Statue für 20 Sekunden",
  "Wechsle 3-mal schnell die Pose",
  "Setz dich hin und steh wieder auf",
  "Setz dich auf den Boden und steh wieder auf",

  // Suchen
  "Finde etwas Rotes",
  "Finde etwas Blaues",
  "Finde etwas Grünes",
  "Finde etwas Gelbes",
  "Finde etwas Schwarzes",
  "Finde etwas Weißes",
  "Finde etwas Graues",
  "Finde etwas Oranges",
  "Finde etwas Rundes",
  "Finde etwas Eckiges",
  "Finde etwas Weiches",
  "Finde etwas Hartes",
  "Finde etwas Kleines",
  "Finde etwas Großes",
  "Finde etwas Langes",
  "Finde etwas Kurzes",
  "Finde etwas Helles",
  "Finde etwas Dunkles",
  "Finde etwas Kaltes",
  "Finde etwas Warmes",
  "Finde etwas aus Holz",
  "Finde etwas aus Metall",
  "Finde etwas aus Plastik",
  "Finde etwas aus Papier",
  "Finde etwas mit Schrift",
  "Finde etwas mit einer Zahl",
  "Finde etwas mit einem Muster",
  "Finde etwas mit einer Ecke",
  "Finde etwas mit mindestens 3 Farben",
  "Finde etwas, das älter aussieht als du",
  "Finde den kleinsten Gegenstand im Raum",
  "Finde den größten Gegenstand im Raum",
  "Finde etwas, das man rollen kann",
  "Finde etwas, das man stapeln kann",
  "Finde etwas, das man tragen kann",
  "Finde etwas, das man werfen könnte",
  "Finde etwas, das man öffnen kann",
  "Finde etwas, das man schließen kann",
  "Finde etwas, das man falten kann",
  "Finde etwas, das Geräusche macht",
  "Finde etwas, das durchsichtig ist",
  "Finde etwas, das glänzt",
  "Finde etwas, das matt ist",
  "Finde etwas mit einem Kreis darauf",
  "Finde etwas mit einer Linie darauf",
  "Finde etwas, das nur eine Farbe hat",
  "Finde etwas, das mehrere Farben hat",
  "Finde etwas, das normalerweise draußen ist",
  "Finde etwas, das normalerweise drinnen ist",
  "Finde etwas, das man zum Sitzen benutzen kann",

  // Sprechen
  "Sag deinen Vornamen",
  "Sag deinen Nachnamen",
  "Sag dein Lieblingsessen",
  "Sag dein Lieblingsgetränk",
  "Sag deine Lieblingsfarbe",
  "Sag dein Lieblingstier",
  "Sag dein Lieblingsspiel",
  "Sag deinen Lieblingsfilm",
  "Sag einen Ländernamen",
  "Sag einen Städtenamen",
  "Sag einen Tiernamen",
  "Sag einen Männernamen",
  "Sag einen Frauennamen",
  "Sag ein Essen",
  "Sag ein Getränk",
  "Sag eine Farbe",
  "Sag einen Beruf",
  "Sag einen Sport",
  "Sag ein Fahrzeug",
  "Sag ein Kleidungsstück",
  "Sag einen Gegenstand",
  "Sag etwas, das man im Sommer macht",
  "Sag etwas, das man im Winter macht",
  "Sag etwas, das man morgens macht",
  "Sag etwas, das man abends macht",
  "Sag etwas, das man in der Schule findet",
  "Sag etwas, das man im Keller findet",
  "Sag etwas, das man in einer Küche findet",
  "Sag etwas, das man draußen findet",
  "Sag etwas, das man nicht essen kann",
  "Sag 3 Tiere",
  "Sag 3 Farben",
  "Sag 3 Städte",
  "Sag 3 Länder",
  "Sag 3 Spiele",
  "Sag 3 Filme",
  "Sag 3 Berufe",
  "Sag 3 Getränke",
  "Sag 3 Kleidungsstücke",
  "Sag 3 Fahrzeuge",
  "Sag 5 Tiere",
  "Sag 5 Lebensmittel",
  "Sag 5 Farben",
  "Sag 5 Städte",
  "Sag 5 Länder",
  "Sag 5 Berufe",
  "Sag 5 Gegenstände",
  "Sag 5 Spiele",
  "Sag 5 Fahrzeuge",
  "Sag 5 Getränke",

  // Denken
  "Zähle von 1 bis 10",
  "Zähle von 10 bis 1",
  "Zähle von 20 bis 1",
  "Zähle in Zweierschritten bis 20",
  "Zähle in Dreierschritten bis 30",
  "Sag das Alphabet so schnell du kannst",
  "Sag das Alphabet rückwärts so weit du kannst",
  "Nenne 3 Wörter mit A",
  "Nenne 3 Wörter mit B",
  "Nenne 3 Wörter mit M",
  "Nenne 3 Wörter mit S",
  "Nenne 3 Wörter mit T",
  "Nenne 3 Tiere mit A",
  "Nenne 3 Tiere mit B",
  "Nenne 3 Tiere mit K",
  "Nenne 3 Länder mit S",
  "Nenne 3 Städte mit B",
  "Nenne 3 Essen mit P",
  "Nenne 3 Getränke mit W",
  "Nenne 3 Spiele",
  "Nenne 3 Dinge, die fliegen",
  "Nenne 3 Dinge, die schwimmen",
  "Nenne 3 Dinge, die rollen",
  "Nenne 3 Dinge, die laut sind",
  "Nenne 3 Dinge, die leise sind",
  "Nenne 3 Dinge, die weich sind",
  "Nenne 3 Dinge, die hart sind",
  "Nenne 3 Dinge, die rund sind",
  "Nenne 3 Dinge, die eckig sind",
  "Nenne 3 Dinge, die man draußen macht",
  "Nenne 5 Dinge, die man in einer Küche findet",
  "Nenne 5 Dinge, die man im Badezimmer findet",
  "Nenne 5 Tiere mit 4 Beinen",
  "Nenne 5 Dinge, die rot sein können",
  "Nenne 5 Dinge, die man tragen kann",
  "Nenne 5 Dinge, die man essen kann",
  "Nenne 5 Dinge, die man trinken kann",
  "Nenne 5 Dinge, die man öffnen kann",
  "Nenne 5 Dinge, die man schließen kann",
  "Nenne 5 Dinge, die Geräusche machen",

  // Lustig
  "Mach dein lustigstes Gesicht",
  "Mach dein ernstestes Gesicht",
  "Mach dein überraschtetes Gesicht",
  "Mach dein verwirrtes Gesicht",
  "Mach dein müdestes Gesicht",
  "Mach dein glücklichstes Gesicht",
  "Mach dein bösestes Gesicht",
  "Mach dein coolstes Gesicht",
  "Mach dein traurigstes Gesicht",
  "Mach dein dümmstes Gesicht",
  "Lächle 10 Sekunden lang",
  "Schau 10 Sekunden komplett ernst",
  "Versuche 10 Sekunden nicht zu lachen",
  "Mach eine völlig unnötige Pose",
  "Mach eine Superheldenpose",
  "Mach eine Filmstar-Pose",
  "Mach eine Model-Pose",
  "Mach eine Fußballer-Pose",
  "Mach eine Siegerpose",
  "Mach eine Niederlagenpose",
  "Laufe wie ein Pinguin",
  "Laufe wie ein Gorilla",
  "Laufe wie eine Katze",
  "Laufe wie ein Hund",
  "Laufe wie ein Dinosaurier",
  "Laufe wie ein Zombie",
  "Laufe wie ein Roboter",
  "Laufe wie ein Model",
  "Tu 10 Sekunden so, als wärst du ein Nachrichtensprecher",
  "Tu 10 Sekunden so, als wärst du ein Roboter",
  "Tu 10 Sekunden so, als wärst du ein König",
  "Tu 10 Sekunden so, als wärst du ein Alien",
  "Tu 10 Sekunden so, als wärst du ein NPC",
  "Mach ein Tiergeräusch",
  "Mach ein Motorgeräusch",
  "Mach ein Robotergeräusch",
  "Mach ein Monstergeräusch",
  "Mach ein Geräusch ohne zu lachen",
  "Erfinde einen völlig sinnlosen Satz",
  "Sag deinen Namen wie ein Nachrichtensprecher",
  "Sag deinen Namen wie ein Roboter",
  "Sag deinen Namen flüsternd",
  "Sag deinen Namen extrem langsam",
  "Sag deinen Namen extrem schnell",
  "Sag einen Satz mit geschlossenen Augen",
  "Sag einen Satz mit übertriebener Dramatik",
  "Sag einen Satz wie ein Bösewicht",
  "Sag einen Satz wie ein Superheld",
  "Sag einen Satz wie ein König",

  // Andere Personen
  "Gib jemandem ein High Five",
  "Gib jemandem einen Fistbump",
  "Frag jemanden nach seinem Lieblingstier",
  "Frag jemanden nach seiner Lieblingsfarbe",
  "Frag jemanden nach seinem Lieblingsessen",
  "Frag jemanden nach seinem Lieblingsspiel",
  "Frag jemanden nach seinem Lieblingsfilm",
  "Sag jemandem etwas Nettes",
  "Bedank dich bei jemandem",
  "Mach mit jemandem gleichzeitig eine Pose",
  "Mach mit jemandem gleichzeitig einen Hampelmann",
  "Setz dich neben eine andere Person",
  "Tausch für 30 Sekunden den Platz mit jemandem",
  "Wähle jemanden für die nächste Aufgabe",
  "Gib jemandem eine eigene Aufgabe",
  "Mach genau dieselbe Bewegung wie eine andere Person",
  "Mach das Gegenteil von dem, was eine andere Person macht",
  "Versuche jemanden zum Lachen zu bringen",
  "Mach mit jemandem einen geheimen Handschlag",
  "Stell jemandem eine völlig zufällige Frage",
  "Frag jemanden nach seinem Lieblingsessen",
  "Frag jemanden nach seinem Lieblingsspiel",
  "Frag jemanden, welches Tier er sein möchte",
  "Frag jemanden, welche Superkraft er wählen würde",
  "Frag jemanden, wohin er gerne reisen würde",
  "Frag jemanden, welchen Beruf er niemals machen würde",
  "Frag jemanden nach seinem Lieblingsfach",
  "Frag jemanden, welches Tier am lustigsten ist",
  "Frag jemanden, welches Essen er jeden Tag essen könnte",
  "Frag jemanden, welches Spiel er mitnehmen würde",

  // Erfinden
  "Erfinde einen neuen Superhelden",
  "Erfinde einen neuen Bösewicht",
  "Erfinde einen neuen Planeten",
  "Erfinde ein neues Tier",
  "Erfinde einen neuen Namen",
  "Erfinde ein neues Essen",
  "Erfinde ein neues Getränk",
  "Erfinde einen neuen Sport",
  "Erfinde ein neues Spiel",
  "Erfinde eine neue App",
  "Erfinde einen neuen Beruf",
  "Erfinde einen neuen Feiertag",
  "Erfinde ein neues Schulfach",
  "Erfinde ein neues Land",
  "Erfinde einen neuen Roboter",
  "Erfinde einen neuen Film",
  "Erfinde einen neuen Filmnamen",
  "Erfinde einen neuen Bandnamen",
  "Erfinde einen neuen Restaurantnamen",
  "Erfinde einen neuen Pizzabelag",
  "Erfinde einen völlig unnötigen Gegenstand",
  "Erfinde eine völlig sinnlose Superkraft",
  "Erfinde einen Namen für einen Dinosaurier",
  "Erfinde einen Namen für ein Raumschiff",
  "Erfinde einen Namen für einen Planeten",
  "Erfinde einen Namen für einen Bösewicht",
  "Erfinde einen Namen für einen Roboter",
  "Erfinde eine neue Regel für dieses Spiel",
  "Erfinde eine Aufgabe für die nächste Person",
  "Erfinde eine 10-Sekunden-Challenge",

  // Mini-Challenges
  "Bleib 10 Sekunden komplett still",
  "Bleib 20 Sekunden komplett still",
  "Steh 10 Sekunden auf einem Bein",
  "Schließ 10 Sekunden die Augen",
  "Schau 10 Sekunden nach oben",
  "Schau 10 Sekunden nach unten",
  "Schau 10 Sekunden geradeaus",
  "Klatsch 5-mal",
  "Klatsch 10-mal",
  "Klatsch einen Rhythmus",
  "Schnipp 5-mal mit den Fingern",
  "Stampfe 5-mal",
  "Stampfe 10-mal",
  "Spring einmal",
  "Spring zweimal",
  "Dreh dich einmal",
  "Dreh dich zweimal",
  "Mach 3 schnelle Bewegungen",
  "Mach 3 langsame Bewegungen",
  "Mach eine Bewegung, die alle nachmachen müssen",
  "Mach eine Bewegung ohne Geräusch",
  "Mach eine Bewegung mit geschlossenen Augen",
  "Berühre 3 verschiedene Gegenstände",
  "Berühre 5 verschiedene Gegenstände",
  "Wechsle deinen Platz",
  "Setz dich auf einen anderen Platz",
  "Steh für 10 Sekunden",
  "Steh für 20 Sekunden",
  "Geh für 10 Sekunden langsam",
  "Geh für 10 Sekunden schnell",

  // Ruhig / Pause
  "Setz dich bequem hin",
  "Mach für 10 Sekunden nichts",
  "Mach für 20 Sekunden nichts",
  "Schau aus dem Fenster",
  "Schau an die Decke",
  "Schau auf den Boden",
  "Schließ kurz die Augen",
  "Atme einmal tief durch",
  "Atme dreimal ruhig durch",
  "Entspann deine Schultern",
  "Streck deine Arme",
  "Streck deine Beine",
  "Lehn dich zurück",
  "Mach eine kurze Pause",
  "Bleib einfach sitzen und warte 10 Sekunden",
  "Schau dich im Raum um",
  "Such dir einen gemütlichen Platz",
  "Mach es dir bequem",
  "Schau für 10 Sekunden niemanden an",
  "Bleib 15 Sekunden ruhig",

  // Kleine Raum-Aufgaben
  "Heb einen Gegenstand vom Boden auf",
  "Stell einen Gegenstand zurück",
  "Rück einen Gegenstand gerade",
  "Rück deinen Stuhl gerade",
  "Richte dein Kissen",
  "Richte deine Decke",
  "Heb 3 Dinge auf",
  "Heb 5 Dinge auf",
  "Mach einen kleinen Weg frei",
  "Stell etwas an seinen Platz",
  "Falte eine Decke",
  "Richte deinen Sitzplatz",
  "Stell einen Gegenstand aufrecht hin",
  "Bring einen Gegenstand an einen anderen Platz",
  "Suche etwas, das falsch herum liegt",
  "Dreh einen Gegenstand richtig herum",
  "Mach deinen Sitzplatz ordentlich",
  "Sammle 3 kleine Dinge ein",
  "Stell 2 Dinge nebeneinander",
  "Finde etwas, das nicht an seinem Platz liegt",

  // Zufällig
  "Wähle jemanden aus, der die nächste Aufgabe macht",
  "Bestimme die nächste Person",
  "Bestimme eine neue Regel für 1 Minute",
  "Alle stehen gleichzeitig auf",
  "Alle setzen sich gleichzeitig hin",
  "Alle klatschen gleichzeitig",
  "Alle machen eine Pose",
  "Alle sagen gleichzeitig ihren Namen",
  "Alle zeigen auf jemanden",
  "Alle drehen sich einmal",
  "Alle machen einen Hampelmann",
  "Alle machen 5 Kniebeugen",
  "Alle stehen auf einem Bein",
  "Alle machen 10 Sekunden lang eine Statue",
  "Alle machen ein Tiergeräusch",
  "Alle machen ein lustiges Gesicht",
  "Alle sagen eine Farbe",
  "Alle sagen ein Tier",
  "Alle sagen ein Essen",
  "Alle sagen einen Städtenamen",
  "Alle wechseln ihren Platz",
  "Alle zeigen auf etwas Rotes",
  "Alle zeigen auf etwas Rundes",
  "Alle zeigen auf etwas Blaues",
  "Alle suchen etwas Kleines",
  "Alle suchen etwas Weiches",
  "Alle suchen etwas Schwarzes",
  "Alle bleiben 10 Sekunden still",
  "Alle lachen absichtlich",
  "Alle machen gleichzeitig eine Siegerpose",
  "Alle machen gleichzeitig eine Roboterbewegung",
  "Alle gehen 5 Schritte",
  "Alle machen eine völlig zufällige Bewegung",
  "Alle denken sich eine neue Aufgabe aus",
  "Jeder nennt ein Tier",
  "Jeder nennt eine Farbe",
  "Jeder nennt ein Essen",
  "Jeder nennt ein Spiel",
  "Jeder nennt eine Stadt",
  "Jeder macht eine eigene Pose",
  "Jeder macht ein eigenes Geräusch",
  "Jeder zeigt auf einen Gegenstand",
  "Jeder sagt ein Wort",
  "Jeder macht eine Bewegung, die alle nachmachen",
  "Jeder nennt eine Superkraft",
  "Jeder nennt ein Lieblingstier",
  "Jeder nennt ein Lieblingsessen",
  "Jeder nennt einen Film",
  "Jeder nennt ein Spiel",

  // Noch mehr Quatsch
  "Tu so, als würdest du gerade einen Preis gewinnen",
  "Tu so, als würdest du im Fernsehen sein",
  "Tu so, als wärst du ein berühmter Schauspieler",
  "Tu so, als wärst du ein Fußballtrainer",
  "Tu so, als wärst du ein Verkäufer",
  "Tu so, als wärst du ein Lehrer",
  "Tu so, als wärst du ein Astronaut",
  "Tu so, als wärst du ein Pilot",
  "Tu so, als wärst du ein König",
  "Tu so, als wärst du ein Zauberer",
  "Tu so, als hättest du gerade im Lotto gewonnen",
  "Tu so, als hättest du gerade etwas Unglaubliches gesehen",
  "Tu so, als würdest du einen Film drehen",
  "Tu so, als würdest du eine Kochshow moderieren",
  "Tu so, als würdest du eine Nachrichtensendung moderieren",
  "Tu so, als würdest du einen Sport kommentieren",
  "Tu so, als würdest du einen Preis verleihen",
  "Tu so, als würdest du einen Alien treffen",
  "Tu so, als würdest du einen Geist sehen",
  "Tu so, als würdest du einen Dinosaurier sehen",
  "Mach 5 Sekunden lang eine Zeitlupenbewegung",
  "Mach 5 Sekunden lang eine Roboterbewegung",
  "Mach 5 Sekunden lang eine Tanzbewegung",
  "Mach 5 Sekunden lang eine Kampfpose",
  "Mach 5 Sekunden lang eine Superheldenpose",
  "Mach 5 Sekunden lang eine Statue",
  "Mach 5 Sekunden lang ein Tier nach",
  "Mach 5 Sekunden lang ein Fahrzeug nach",
  "Mach 5 Sekunden lang einen Roboter nach",
  "Mach 5 Sekunden lang einen NPC nach",
    // Neue Bewegung

  "Gehe seitwärts durch den Raum",
  "Gehe 10 Schritte seitwärts",
  "Gehe 10 Schritte mit übertrieben großen Schritten",
  "Gehe 10 Schritte mit winzigen Schritten",
  "Gehe 5 Schritte wie ein Riese",
  "Gehe 5 Schritte wie ein Zwerg",
  "Hüpfe auf einem Bein bis zur nächsten Wand",
  "Wechsle beim Hüpfen nach 5 Sprüngen das Bein",
  "Laufe auf der Stelle und zähle bis 15",
  "Mache 10 Sekunden lang langsame Bewegungen",
  "Mache 10 Sekunden lang schnelle Bewegungen",
  "Bewege nur deine Arme für 10 Sekunden",
  "Bewege nur deine Beine für 10 Sekunden",
  "Bewege nur deinen Kopf für 5 Sekunden",
  "Bewege dich 10 Sekunden lang ohne deine Arme zu benutzen",
  "Laufe 5 Schritte und bleib plötzlich stehen",
  "Mach drei Schritte und dreh dich dann um",
  "Gehe zur Wand und wieder zurück",
  "Gehe zur Tür und wieder zurück",
  "Berühre mit deinem Fuß eine Wand",
  "Berühre mit deinem Ellenbogen dein Knie",
  "Versuche deine Zehen mit den Händen zu berühren",
  "Streck dich so weit nach links wie möglich",
  "Streck dich so weit nach rechts wie möglich",
  "Streck dich nach vorne",
  "Streck dich nach hinten",
  "Zieh deine Schultern 5-mal hoch",
  "Kreise deine Schultern 5-mal",
  "Wackle 10 Sekunden mit deinen Fingern",
  "Wackle 10 Sekunden mit deinen Zehen",
  "Balanciere einen Moment auf einem Bein",
  "Wechsle dreimal zwischen beiden Beinen",
  "Mach eine Kniebeuge und bleib unten",
  "Mach eine Kniebeuge und streck dich danach ganz nach oben",
  "Mach zwei Kniebeugen hintereinander",
  "Mach fünf kleine Sprünge",
  "Mach drei große Sprünge",
  "Hüpfe einmal nach links und einmal nach rechts",
  "Springe einmal nach vorne und zurück",
  "Mach einen Schritt nach vorne und zwei zurück",
  "Laufe eine kleine Runde im Raum",
  "Gehe einmal um eine Person herum",
  "Gehe einmal um einen Gegenstand herum",
  "Laufe zur Wand und klatsch einmal",
  "Gehe zur Tür und dreh dich dort einmal um",
  "Mache eine Bewegung und friere danach ein",
  "Mache drei Bewegungen hintereinander",
  "Mache eine Bewegung, die niemand erwartet",
  "Mache die langsamste Bewegung, die dir einfällt",

  // Neue Suchaufgaben

  "Finde etwas mit mehr als vier Ecken",
  "Finde etwas, das zwei verschiedene Materialien hat",
  "Finde etwas, das man zusammenklappen kann",
  "Finde etwas, das man drehen kann",
  "Finde etwas, das einen Deckel hat",
  "Finde etwas, das einen Griff hat",
  "Finde etwas, das zwei gleiche Seiten hat",
  "Finde etwas mit einem Buchstaben darauf",
  "Finde etwas mit einem Bild darauf",
  "Finde etwas mit einem Tier darauf",
  "Finde etwas mit einem Gesicht darauf",
  "Finde etwas, das kleiner als deine Hand ist",
  "Finde etwas, das größer als dein Kopf ist",
  "Finde etwas, das schwer aussieht",
  "Finde etwas, das leicht aussieht",
  "Finde etwas, das man zusammenrollen kann",
  "Finde etwas, das man auseinandernehmen könnte",
  "Finde etwas mit einer geraden Linie",
  "Finde etwas mit einer gebogenen Linie",
  "Finde etwas, das ungefähr quadratisch ist",
  "Finde etwas, das ungefähr dreieckig ist",
  "Finde etwas, das man stapeln könnte",
  "Finde etwas, das man als Sitz benutzen könnte",
  "Finde etwas, das man als Tisch benutzen könnte",
  "Finde etwas, das man als Schild benutzen könnte",
  "Finde etwas, das man als Hut benutzen könnte",
  "Finde etwas, das zwei gleiche Farben hat",
  "Finde etwas mit genau einer sichtbaren Zahl",
  "Finde etwas, das du heute noch nicht benutzt hast",
  "Finde etwas, das wahrscheinlich älter als 5 Jahre ist",
  "Finde etwas, das wahrscheinlich jünger als 5 Jahre ist",
  "Finde etwas, das ganz nah bei dir liegt",
  "Finde etwas, das weit von dir entfernt liegt",
  "Finde etwas über Kopfhöhe",
  "Finde etwas unter Kniehöhe",
  "Finde etwas, das auf dem Boden steht",
  "Finde etwas, das an einer Wand hängt",
  "Finde etwas, das auf einem Tisch liegt",
  "Finde etwas, das man leicht übersehen kann",
  "Finde etwas, das du vorher noch nicht bemerkt hast",
  "Finde etwas, das zwei verschiedene Formen hat",
  "Finde etwas, das ungefähr gleich groß wie deine Hand ist",
  "Finde etwas, das du mit einem Finger bewegen kannst",
  "Finde etwas, das sich nicht leicht bewegen lässt",
  "Finde etwas, das man hören kann",
  "Finde etwas, das man riechen kann",
  "Finde etwas, das einen Schatten wirft",
  "Finde etwas, das Licht reflektiert",
  "Finde etwas, das mehrere Teile hat",
  "Finde etwas, das alleine steht",

  // Neue schnelle Aufgaben

  "Klatsch dreimal und sag deinen Namen",
  "Stampfe einmal und setz dich hin",
  "Spring einmal und sag eine Farbe",
  "Dreh dich um und sag ein Tier",
  "Mach eine Pose und halte sie 5 Sekunden",
  "Berühre den Boden und danach die Decke mit dem Blick",
  "Steh auf und setz dich sofort wieder hin",
  "Sag ein Wort und klatsch danach",
  "Sag eine Zahl und stampfe danach",
  "Sag eine Farbe und zeig auf etwas mit dieser Farbe",
  "Nenne ein Tier und mach das Geräusch dazu",
  "Nenne ein Fahrzeug und mach das Geräusch dazu",
  "Nenne ein Essen und mach eine passende Bewegung",
  "Nenne eine Farbe und suche sie im Raum",
  "Nenne einen Gegenstand und zeig darauf",
  "Nenne einen Namen, der mit A beginnt",
  "Nenne einen Namen, der mit M beginnt",
  "Nenne einen Namen, der mit S beginnt",
  "Nenne ein Wort mit genau vier Buchstaben",
  "Nenne ein Wort mit genau fünf Buchstaben",
  "Nenne ein Wort mit mehr als acht Buchstaben",
  "Sag das erste Wort, das dir einfällt",
  "Sag das Gegenteil von laut",
  "Sag das Gegenteil von groß",
  "Sag das Gegenteil von schnell",
  "Sag das Gegenteil von hell",
  "Sag das Gegenteil von oben",
  "Sag einen Satz, der mit „Heute“ beginnt",
  "Sag einen Satz, der mit „Morgen“ beginnt",
  "Sag einen Satz, der keinen Sinn ergibt",

  // Neue Denkaufgaben

  "Nenne etwas, das man nur selten braucht",
  "Nenne etwas, das fast jeder besitzt",
  "Nenne etwas, das man niemals in den Kühlschrank legen würde",
  "Nenne etwas, das man auf keinen Fall fallen lassen möchte",
  "Nenne etwas, das sehr laut sein kann",
  "Nenne etwas, das fast lautlos sein kann",
  "Nenne etwas, das man morgens dringend braucht",
  "Nenne etwas, das man nachts braucht",
  "Nenne etwas, das man nur draußen benutzt",
  "Nenne etwas, das man nur drinnen benutzt",
  "Nenne etwas, das man mit zwei Händen benutzt",
  "Nenne etwas, das man mit nur einem Finger bedienen kann",
  "Nenne etwas, das man niemals alleine tragen würde",
  "Nenne etwas, das man normalerweise verliert",
  "Nenne etwas, das man normalerweise sucht",
  "Nenne etwas, das man verschenken kann",
  "Nenne etwas, das man sammeln kann",
  "Nenne etwas, das man reparieren kann",
  "Nenne etwas, das kaputtgehen kann",
  "Nenne etwas, das man einschalten kann",
  "Nenne etwas, das man ausschalten kann",
  "Nenne etwas, das man aufladen kann",
  "Nenne etwas, das man verlieren und wiederfinden kann",
  "Nenne etwas, das man in eine Tasche stecken kann",
  "Nenne etwas, das niemals in eine Tasche passen würde",
  "Nenne etwas, das man anziehen kann",
  "Nenne etwas, das man ausziehen kann",
  "Nenne etwas, das man werfen und fangen kann",
  "Nenne etwas, das man nur schwer erklären kann",
  "Nenne etwas, das sofort gute Laune machen kann",
  "Nenne etwas, das dich sofort nerven würde",
  "Nenne etwas, das du gerne einmal ausprobieren würdest",
  "Nenne etwas, das du niemals essen würdest",
  "Nenne etwas, das du gerne besitzen würdest",
  "Nenne etwas, das du als Superkraft haben möchtest",
  "Nenne etwas, das als Geschenk cool wäre",
  "Nenne etwas, das man in einem Keller erwarten würde",
  "Nenne etwas, das man auf einem Dach erwarten würde",
  "Nenne etwas, das man auf einer Insel erwarten würde",
  "Nenne etwas, das man im Weltall nicht braucht",

  // Neue lustige Aufgaben

  "Sprich 10 Sekunden mit einer unsichtbaren Person",
  "Begrüße einen Gegenstand im Raum",
  "Verabschiede dich dramatisch von einem Gegenstand",
  "Tu so, als wäre dein Stuhl dein größter Feind",
  "Tu so, als wäre der Boden extrem heiß",
  "Tu so, als wäre der Boden aus Eis",
  "Tu so, als würdest du gerade schweben",
  "Tu so, als könntest du unsichtbar werden",
  "Tu so, als wäre jemand hinter dir",
  "Tu so, als hättest du gerade eine geniale Idee",
  "Tu so, als hättest du etwas komplett vergessen",
  "Tu so, als würdest du gerade auf einer Bühne stehen",
  "Tu so, als würdest du einen Pokal gewinnen",
  "Tu so, als würdest du einen schlechten Zaubertrick vorführen",
  "Tu so, als würdest du einen Werbespot drehen",
  "Tu so, als würdest du eine neue Erfindung präsentieren",
  "Tu so, als würdest du einen sehr schlechten Witz erzählen",
  "Tu so, als würdest du etwas verkaufen, das niemand braucht",
  "Tu so, als würdest du einen unsichtbaren Ball fangen",
  "Tu so, als würdest du gegen einen unsichtbaren Gegner kämpfen",
  "Tu so, als würdest du einen unsichtbaren Hund streicheln",
  "Tu so, als würdest du einen unsichtbaren Knopf drücken",
  "Tu so, als würdest du einen unsichtbaren Koffer tragen",
  "Tu so, als würdest du auf einer unsichtbaren Treppe laufen",
  "Tu so, als würdest du einen unsichtbaren Regenschirm halten",
  "Tu so, als würdest du gerade aufwachen",
  "Tu so, als würdest du gerade einschlafen",
  "Tu so, als würdest du einen Marathon gewinnen",
  "Tu so, als würdest du gerade deinen Führerschein bekommen",
  "Tu so, als würdest du gerade einen Preis für nichts gewinnen",
  "Mach eine dramatische Verbeugung",
  "Mach eine völlig übertriebene Begrüßung",
  "Mach eine völlig übertriebene Verabschiedung",
  "Mach eine Pose, die absolut keinen Sinn ergibt",
  "Mach eine Bewegung und gib ihr einen Namen",
  "Erfinde einen Namen für deine aktuelle Pose",
  "Erfinde einen Namen für deinen Gang",
  "Erfinde einen Namen für dein Geräusch",
  "Erfinde einen Namen für deine Superkraft",
  "Erfinde eine völlig sinnlose Regel",

  // Neue soziale Aufgaben

  "Such dir jemanden aus und macht gleichzeitig eine Pose",
  "Such dir jemanden aus und macht gleichzeitig eine Drehung",
  "Such dir jemanden aus und macht gleichzeitig eine Kniebeuge",
  "Such dir jemanden aus und geht gleichzeitig drei Schritte",
  "Such dir jemanden aus und sagt gleichzeitig ein Wort",
  "Such dir jemanden aus und zeigt gleichzeitig auf etwas",
  "Such dir jemanden aus und gebt euch ein High Five",
  "Such dir jemanden aus und macht gleichzeitig ein Tiergeräusch",
  "Such dir jemanden aus und macht gleichzeitig ein lustiges Gesicht",
  "Such dir jemanden aus und bleibt beide 10 Sekunden still",
  "Sag jemandem, welche Superkraft zu ihm passen würde",
  "Sag jemandem, welches Tier zu ihm passen würde",
  "Sag jemandem, welche Farbe zu ihm passen würde",
  "Sag jemandem einen erfundenen Spitznamen",
  "Frag jemanden nach seiner Lieblingsjahreszeit",
  "Frag jemanden nach seinem Lieblingssport",
  "Frag jemanden nach seinem Lieblingsessen als Kind",
  "Frag jemanden, welches Tier er gerne einmal sehen würde",
  "Frag jemanden, welche Superkraft er nicht haben möchte",
  "Frag jemanden, welchen Gegenstand er auf eine einsame Insel mitnehmen würde",
  "Frag jemanden, welchen Film er gerne vergessen und neu schauen würde",
  "Frag jemanden, welches Spiel er gerne zum ersten Mal wieder spielen würde",
  "Frag jemanden, welches Essen er niemals probieren würde",
  "Frag jemanden, welcher Beruf lustig wäre",
  "Frag jemanden, welches Tier er niemals als Haustier haben möchte",
  "Lass jemand anderen eine Pose bestimmen",
  "Lass jemand anderen dein nächstes Wort bestimmen",
  "Lass jemand anderen eine Farbe nennen und finde sie",
  "Lass jemand anderen eine Zahl zwischen 1 und 10 nennen und mache so viele Bewegungen",
  "Lass jemand anderen dein Tiergeräusch bestimmen",

  // Neue Gruppenaufgaben

  "Alle stehen hintereinander",
  "Alle stellen sich nebeneinander",
  "Alle setzen sich in einen Kreis",
  "Alle zeigen auf die Tür",
  "Alle zeigen auf den Boden",
  "Alle zeigen zur Decke",
  "Alle zeigen auf etwas Blaues",
  "Alle zeigen auf etwas Grünes",
  "Alle zeigen auf etwas Rundes",
  "Alle zeigen auf etwas Kleines",
  "Alle machen dieselbe Pose",
  "Alle machen unterschiedliche Posen",
  "Alle gehen drei Schritte nach vorne",
  "Alle gehen drei Schritte zurück",
  "Alle drehen sich nach links",
  "Alle drehen sich nach rechts",
  "Alle wechseln ihre Plätze",
  "Alle machen eine Bewegung in Zeitlupe",
  "Alle machen eine schnelle Bewegung",
  "Alle machen eine Roboterbewegung",
  "Alle machen eine Tierbewegung",
  "Alle machen gleichzeitig ein Geräusch",
  "Alle sagen gleichzeitig eine Zahl",
  "Alle sagen gleichzeitig eine Farbe",
  "Alle sagen gleichzeitig ein Tier",
  "Alle sagen gleichzeitig ein Essen",
  "Alle bleiben stehen, bis jemand lacht",
  "Alle versuchen gleichzeitig ernst zu bleiben",
  "Alle machen eine gemeinsame Siegerpose",
  "Alle erfinden gleichzeitig eine eigene Pose",

  // Neue kreative Aufgaben

  "Erfinde einen Namen für dieses Zimmer",
  "Erfinde einen Namen für diesen Abend",
  "Erfinde einen Namen für diese Gruppe",
  "Erfinde einen neuen Feiertag für morgen",
  "Erfinde ein neues Schulfach",
  "Erfinde eine neue Sportart",
  "Erfinde eine neue Eissorte",
  "Erfinde einen neuen Süßigkeitennamen",
  "Erfinde einen neuen Fantasienamen",
  "Erfinde einen Namen für ein Monster",
  "Erfinde einen Namen für ein Haustier",
  "Erfinde einen Namen für ein Königreich",
  "Erfinde einen Namen für eine Insel",
  "Erfinde einen Namen für eine Stadt",
  "Erfinde einen Namen für ein Hotel",
  "Erfinde einen Namen für eine Spielekonsole",
  "Erfinde einen Namen für ein Videospiel",
  "Erfinde einen Namen für eine Band",
  "Erfinde einen Namen für einen YouTube-Kanal",
  "Erfinde einen Namen für einen Supermarkt",
  "Erfinde einen Gegenstand, der völlig nutzlos ist",
  "Erfinde einen Gegenstand, den jeder brauchen würde",
  "Erfinde eine Superkraft mit einem völlig nutzlosen Effekt",
  "Erfinde ein Tier, das zwei echte Tiere kombiniert",
  "Erfinde ein Essen aus drei zufälligen Zutaten",
  "Erfinde einen Film mit einem möglichst schlechten Titel",
  "Erfinde ein Spiel, das man ohne Gegenstände spielen kann",
  "Erfinde eine neue Regel für die nächsten zwei Aufgaben",
  "Erfinde eine Aufgabe, bei der niemand sprechen darf",
  "Erfinde eine Aufgabe, bei der alle gleichzeitig etwas machen",

  // Neue kurze Quatsch-Aufgaben

  "Sag „Was passiert hier eigentlich?“",
  "Sag „Das war so geplant“",
  "Sag „Ich habe einen Plan“ und mach dann eine Pose",
  "Sag „Nein“ in drei verschiedenen Stimmen",
  "Sag „Ja“ in drei verschiedenen Stimmen",
  "Sag ein Wort mit einer möglichst dramatischen Stimme",
  "Sag deinen Namen wie ein Bösewicht",
  "Sag deinen Namen wie ein Nachrichtensprecher",
  "Sag deinen Namen wie ein Sportkommentator",
  "Sag deinen Namen wie ein König",
  "Sag einen Satz, als wärst du extrem überrascht",
  "Sag einen Satz, als wärst du extrem gelangweilt",
  "Sag einen Satz, als wärst du gerade sehr glücklich",
  "Sag einen Satz, als wärst du extrem verwirrt",
  "Sag einen Satz, als wärst du ein Roboter",
  "Sag einen Satz, als wärst du ein Alien",
  "Sag einen Satz, als wärst du ein Pirat",
  "Sag einen Satz, als wärst du ein Ritter",
  "Sag einen Satz, als wärst du ein Zauberer",
  "Sag einen Satz, als wärst du ein Bösewicht",

  // Neue kleine Challenges

  "Halte deine Hände 10 Sekunden über deinen Kopf",
  "Halte deine Arme 10 Sekunden ausgestreckt",
  "Halte eine Pose 15 Sekunden",
  "Steh 15 Sekunden auf einem Bein",
  "Bleib 15 Sekunden ohne zu blinzeln",
  "Bleib 10 Sekunden ohne zu sprechen",
  "Bleib 10 Sekunden ohne dich zu bewegen",
  "Mach 10 Sekunden lang nur kleine Bewegungen",
  "Mach 10 Sekunden lang nur große Bewegungen",
  "Mach fünf Bewegungen hintereinander ohne Pause",
  "Mach eine Bewegung rückwärts und danach dieselbe vorwärts",
  "Mach eine Bewegung mit der linken Seite",
  "Mach eine Bewegung mit der rechten Seite",
  "Wechsle fünfmal zwischen Sitzen und Stehen",
  "Mach drei verschiedene Gesichtsausdrücke hintereinander",
  "Mach drei verschiedene Posen hintereinander",
  "Klatsch einen Rhythmus und wiederhole ihn",
  "Klatsch einen Rhythmus, den jemand anderes nachmachen muss",
  "Mach einen Rhythmus mit deinen Füßen",
  "Mach einen Rhythmus mit deinen Händen",

  // Neue zufällige Aufgaben

  "Zeig auf den Gegenstand, den du am interessantesten findest",
  "Zeig auf den Gegenstand, den du am wenigsten interessant findest",
  "Zeig auf etwas, das du heute schon benutzt hast",
  "Zeig auf etwas, das du heute noch nicht benutzt hast",
  "Zeig auf etwas, das du gerne mitnehmen würdest",
  "Zeig auf etwas, das du nicht mitnehmen würdest",
  "Such dir einen Gegenstand aus und gib ihm einen Namen",
  "Such dir einen Gegenstand aus und erfinde seine Superkraft",
  "Such dir einen Gegenstand aus und erfinde seine Geschichte",
  "Such dir einen Gegenstand aus und tu so, als wäre er wertvoll",
  "Wähle eine Person und gib ihr eine zufällige Aufgabe",
  "Wähle eine Person und bestimme ihre nächste Pose",
  "Wähle eine Person und bestimme ein Tiergeräusch",
  "Wähle eine Farbe und finde etwas in dieser Farbe",
  "Wähle eine Zahl zwischen 1 und 10",
  "Wähle eine Zahl und klatsche so oft",
  "Wähle einen Gegenstand und berühre ihn",
  "Wähle einen Gegenstand und stelle ihn gerade hin",
  "Wähle einen Platz und setz dich dort hin",
  "Wähle jemanden, der als Nächstes die Aufgabe auswählen darf",
];