export const tasks = [
  // Bewegung
  "Mach 5 Kniebeugen",
  "Mach 10 Kniebeugen",
  "Mach 15 Kniebeugen",
  "Mach 5 Hampelmänner",
  "Mach 10 Hampelmänner",
  "Mach 15 Hampelmänner",
  "Hüpfe 10-mal auf der Stelle",
  "Hüpfe 20-mal auf der Stelle",
  "Laufe einmal durch den Raum",
  "Laufe zweimal durch den Raum",
  "Gehe einmal rückwärts durch den Raum",
  "Gehe auf Zehenspitzen durch den Raum",
  "Gehe auf den Fersen durch den Raum",
  "Laufe im Kreis",
  "Dreh dich 3-mal im Kreis",
  "Dreh dich 5-mal im Kreis",
  "Steh 10 Sekunden auf einem Bein",
  "Steh 20 Sekunden auf einem Bein",
  "Wechsle nach 5 Sekunden das Bein",
  "Berühre den Boden",
  "Berühre die Wand",
  "Berühre eine Tür",
  "Berühre deinen Kopf mit beiden Händen",
  "Berühre deine Knie",
  "Streck beide Arme nach oben",
  "Streck beide Arme zur Seite",
  "Mach dich so groß wie möglich",
  "Mach dich so klein wie möglich",
  "Streck dich einmal richtig",
  "Schüttel beide Arme aus",
  "Schüttel beide Beine aus",
  "Spring einmal so hoch du kannst",
  "Mach einen kleinen Freudentanz",
  "Laufe 5 Sekunden auf der Stelle",
  "Bewege dich 10 Sekunden wie ein Roboter",
  "Bewege dich 10 Sekunden in Zeitlupe",
  "Laufe wie ein Pinguin",
  "Laufe wie ein Roboter",
  "Laufe wie ein Dinosaurier",
  "Laufe wie ein Cowboy",
  "Laufe wie ein Superheld",
  "Schleiche einmal durch den Raum",
  "Marschier einmal durch den Raum",
  "Mach eine Siegerpose",
  "Mach eine dramatische Pose",
  "Mach eine Statue für 10 Sekunden",
  "Mach eine Statue für 20 Sekunden",
  "Wechsle 3-mal schnell die Pose",
  "Setz dich hin und steh wieder auf",
  "Setz dich auf den Boden und steh wieder auf",

  // Suchen
  "Finde etwas Rotes",
  "Finde etwas Blaues",
  "Finde etwas Grünes",
  "Finde etwas Gelbes",
  "Finde etwas Schwarzes",
  "Finde etwas Weißes",
  "Finde etwas Graues",
  "Finde etwas Oranges",
  "Finde etwas Rundes",
  "Finde etwas Eckiges",
  "Finde etwas Weiches",
  "Finde etwas Hartes",
  "Finde etwas Kleines",
  "Finde etwas Großes",
  "Finde etwas Langes",
  "Finde etwas Kurzes",
  "Finde etwas Helles",
  "Finde etwas Dunkles",
  "Finde etwas Kaltes",
  "Finde etwas Warmes",
  "Finde etwas aus Holz",
  "Finde etwas aus Metall",
  "Finde etwas aus Plastik",
  "Finde etwas aus Papier",
  "Finde etwas mit Schrift",
  "Finde etwas mit einer Zahl",
  "Finde etwas mit einem Muster",
  "Finde etwas mit einer Ecke",
  "Finde etwas mit mindestens 3 Farben",
  "Finde etwas, das älter aussieht als du",
  "Finde den kleinsten Gegenstand im Raum",
  "Finde den größten Gegenstand im Raum",
  "Finde etwas, das man rollen kann",
  "Finde etwas, das man stapeln kann",
  "Finde etwas, das man tragen kann",
  "Finde etwas, das man werfen könnte",
  "Finde etwas, das man öffnen kann",
  "Finde etwas, das man schließen kann",
  "Finde etwas, das man falten kann",
  "Finde etwas, das Geräusche macht",
  "Finde etwas, das durchsichtig ist",
  "Finde etwas, das glänzt",
  "Finde etwas, das matt ist",
  "Finde etwas mit einem Kreis darauf",
  "Finde etwas mit einer Linie darauf",
  "Finde etwas, das nur eine Farbe hat",
  "Finde etwas, das mehrere Farben hat",
  "Finde etwas, das normalerweise draußen ist",
  "Finde etwas, das normalerweise drinnen ist",
  "Finde etwas, das man zum Sitzen benutzen kann",

  // Sprechen
  "Sag deinen Vornamen",
  "Sag deinen Nachnamen",
  "Sag dein Lieblingsessen",
  "Sag dein Lieblingsgetränk",
  "Sag deine Lieblingsfarbe",
  "Sag dein Lieblingstier",
  "Sag dein Lieblingsspiel",
  "Sag deinen Lieblingsfilm",
  "Sag einen Ländernamen",
  "Sag einen Städtenamen",
  "Sag einen Tiernamen",
  "Sag einen Männernamen",
  "Sag einen Frauennamen",
  "Sag ein Essen",
  "Sag ein Getränk",
  "Sag eine Farbe",
  "Sag einen Beruf",
  "Sag einen Sport",
  "Sag ein Fahrzeug",
  "Sag ein Kleidungsstück",
  "Sag einen Gegenstand",
  "Sag etwas, das man im Sommer macht",
  "Sag etwas, das man im Winter macht",
  "Sag etwas, das man morgens macht",
  "Sag etwas, das man abends macht",
  "Sag etwas, das man in der Schule findet",
  "Sag etwas, das man im Keller findet",
  "Sag etwas, das man in einer Küche findet",
  "Sag etwas, das man draußen findet",
  "Sag etwas, das man nicht essen kann",
  "Sag 3 Tiere",
  "Sag 3 Farben",
  "Sag 3 Städte",
  "Sag 3 Länder",
  "Sag 3 Spiele",
  "Sag 3 Filme",
  "Sag 3 Berufe",
  "Sag 3 Getränke",
  "Sag 3 Kleidungsstücke",
  "Sag 3 Fahrzeuge",
  "Sag 5 Tiere",
  "Sag 5 Lebensmittel",
  "Sag 5 Farben",
  "Sag 5 Städte",
  "Sag 5 Länder",
  "Sag 5 Berufe",
  "Sag 5 Gegenstände",
  "Sag 5 Spiele",
  "Sag 5 Fahrzeuge",
  "Sag 5 Getränke",

  // Denken
  "Zähle von 1 bis 10",
  "Zähle von 10 bis 1",
  "Zähle von 20 bis 1",
  "Zähle in Zweierschritten bis 20",
  "Zähle in Dreierschritten bis 30",
  "Sag das Alphabet so schnell du kannst",
  "Sag das Alphabet rückwärts so weit du kannst",
  "Nenne 3 Wörter mit A",
  "Nenne 3 Wörter mit B",
  "Nenne 3 Wörter mit M",
  "Nenne 3 Wörter mit S",
  "Nenne 3 Wörter mit T",
  "Nenne 3 Tiere mit A",
  "Nenne 3 Tiere mit B",
  "Nenne 3 Tiere mit K",
  "Nenne 3 Länder mit S",
  "Nenne 3 Städte mit B",
  "Nenne 3 Essen mit P",
  "Nenne 3 Getränke mit W",
  "Nenne 3 Spiele",
  "Nenne 3 Dinge, die fliegen",
  "Nenne 3 Dinge, die schwimmen",
  "Nenne 3 Dinge, die rollen",
  "Nenne 3 Dinge, die laut sind",
  "Nenne 3 Dinge, die leise sind",
  "Nenne 3 Dinge, die weich sind",
  "Nenne 3 Dinge, die hart sind",
  "Nenne 3 Dinge, die rund sind",
  "Nenne 3 Dinge, die eckig sind",
  "Nenne 3 Dinge, die man draußen macht",
  "Nenne 5 Dinge, die man in einer Küche findet",
  "Nenne 5 Dinge, die man im Badezimmer findet",
  "Nenne 5 Tiere mit 4 Beinen",
  "Nenne 5 Dinge, die rot sein können",
  "Nenne 5 Dinge, die man tragen kann",
  "Nenne 5 Dinge, die man essen kann",
  "Nenne 5 Dinge, die man trinken kann",
  "Nenne 5 Dinge, die man öffnen kann",
  "Nenne 5 Dinge, die man schließen kann",
  "Nenne 5 Dinge, die Geräusche machen",

  // Lustig
  "Mach dein lustigstes Gesicht",
  "Mach dein ernstestes Gesicht",
  "Mach dein überraschtetes Gesicht",
  "Mach dein verwirrtes Gesicht",
  "Mach dein müdestes Gesicht",
  "Mach dein glücklichstes Gesicht",
  "Mach dein bösestes Gesicht",
  "Mach dein coolstes Gesicht",
  "Mach dein traurigstes Gesicht",
  "Mach dein dümmstes Gesicht",
  "Lächle 10 Sekunden lang",
  "Schau 10 Sekunden komplett ernst",
  "Versuche 10 Sekunden nicht zu lachen",
  "Mach eine völlig unnötige Pose",
  "Mach eine Superheldenpose",
  "Mach eine Filmstar-Pose",
  "Mach eine Model-Pose",
  "Mach eine Fußballer-Pose",
  "Mach eine Siegerpose",
  "Mach eine Niederlagenpose",
  "Laufe wie ein Pinguin",
  "Laufe wie ein Gorilla",
  "Laufe wie eine Katze",
  "Laufe wie ein Hund",
  "Laufe wie ein Dinosaurier",
  "Laufe wie ein Zombie",
  "Laufe wie ein Roboter",
  "Laufe wie ein Model",
  "Tu 10 Sekunden so, als wärst du ein Nachrichtensprecher",
  "Tu 10 Sekunden so, als wärst du ein Roboter",
  "Tu 10 Sekunden so, als wärst du ein König",
  "Tu 10 Sekunden so, als wärst du ein Alien",
  "Tu 10 Sekunden so, als wärst du ein NPC",
  "Mach ein Tiergeräusch",
  "Mach ein Motorgeräusch",
  "Mach ein Robotergeräusch",
  "Mach ein Monstergeräusch",
  "Mach ein Geräusch ohne zu lachen",
  "Erfinde einen völlig sinnlosen Satz",
  "Sag deinen Namen wie ein Nachrichtensprecher",
  "Sag deinen Namen wie ein Roboter",
  "Sag deinen Namen flüsternd",
  "Sag deinen Namen extrem langsam",
  "Sag deinen Namen extrem schnell",
  "Sag einen Satz mit geschlossenen Augen",
  "Sag einen Satz mit übertriebener Dramatik",
  "Sag einen Satz wie ein Bösewicht",
  "Sag einen Satz wie ein Superheld",
  "Sag einen Satz wie ein König",

  // Andere Personen
  "Gib jemandem ein High Five",
  "Gib jemandem einen Fistbump",
  "Frag jemanden nach seinem Lieblingstier",
  "Frag jemanden nach seiner Lieblingsfarbe",
  "Frag jemanden nach seinem Lieblingsessen",
  "Frag jemanden nach seinem Lieblingsspiel",
  "Frag jemanden nach seinem Lieblingsfilm",
  "Sag jemandem etwas Nettes",
  "Bedank dich bei jemandem",
  "Mach mit jemandem gleichzeitig eine Pose",
  "Mach mit jemandem gleichzeitig einen Hampelmann",
  "Setz dich neben eine andere Person",
  "Tausch für 30 Sekunden den Platz mit jemandem",
  "Wähle jemanden für die nächste Aufgabe",
  "Gib jemandem eine eigene Aufgabe",
  "Mach genau dieselbe Bewegung wie eine andere Person",
  "Mach das Gegenteil von dem, was eine andere Person macht",
  "Versuche jemanden zum Lachen zu bringen",
  "Mach mit jemandem einen geheimen Handschlag",
  "Stell jemandem eine völlig zufällige Frage",
  "Frag jemanden nach seinem Lieblingsessen",
  "Frag jemanden nach seinem Lieblingsspiel",
  "Frag jemanden, welches Tier er sein möchte",
  "Frag jemanden, welche Superkraft er wählen würde",
  "Frag jemanden, wohin er gerne reisen würde",
  "Frag jemanden, welchen Beruf er niemals machen würde",
  "Frag jemanden nach seinem Lieblingsfach",
  "Frag jemanden, welches Tier am lustigsten ist",
  "Frag jemanden, welches Essen er jeden Tag essen könnte",
  "Frag jemanden, welches Spiel er mitnehmen würde",

  // Erfinden
  "Erfinde einen neuen Superhelden",
  "Erfinde einen neuen Bösewicht",
  "Erfinde einen neuen Planeten",
  "Erfinde ein neues Tier",
  "Erfinde einen neuen Namen",
  "Erfinde ein neues Essen",
  "Erfinde ein neues Getränk",
  "Erfinde einen neuen Sport",
  "Erfinde ein neues Spiel",
  "Erfinde eine neue App",
  "Erfinde einen neuen Beruf",
  "Erfinde einen neuen Feiertag",
  "Erfinde ein neues Schulfach",
  "Erfinde ein neues Land",
  "Erfinde einen neuen Roboter",
  "Erfinde einen neuen Film",
  "Erfinde einen neuen Filmnamen",
  "Erfinde einen neuen Bandnamen",
  "Erfinde einen neuen Restaurantnamen",
  "Erfinde einen neuen Pizzabelag",
  "Erfinde einen völlig unnötigen Gegenstand",
  "Erfinde eine völlig sinnlose Superkraft",
  "Erfinde einen Namen für einen Dinosaurier",
  "Erfinde einen Namen für ein Raumschiff",
  "Erfinde einen Namen für einen Planeten",
  "Erfinde einen Namen für einen Bösewicht",
  "Erfinde einen Namen für einen Roboter",
  "Erfinde eine neue Regel für dieses Spiel",
  "Erfinde eine Aufgabe für die nächste Person",
  "Erfinde eine 10-Sekunden-Challenge",

  // Mini-Challenges
  "Bleib 10 Sekunden komplett still",
  "Bleib 20 Sekunden komplett still",
  "Steh 10 Sekunden auf einem Bein",
  "Schließ 10 Sekunden die Augen",
  "Schau 10 Sekunden nach oben",
  "Schau 10 Sekunden nach unten",
  "Schau 10 Sekunden geradeaus",
  "Klatsch 5-mal",
  "Klatsch 10-mal",
  "Klatsch einen Rhythmus",
  "Schnipp 5-mal mit den Fingern",
  "Stampfe 5-mal",
  "Stampfe 10-mal",
  "Spring einmal",
  "Spring zweimal",
  "Dreh dich einmal",
  "Dreh dich zweimal",
  "Mach 3 schnelle Bewegungen",
  "Mach 3 langsame Bewegungen",
  "Mach eine Bewegung, die alle nachmachen müssen",
  "Mach eine Bewegung ohne Geräusch",
  "Mach eine Bewegung mit geschlossenen Augen",
  "Berühre 3 verschiedene Gegenstände",
  "Berühre 5 verschiedene Gegenstände",
  "Wechsle deinen Platz",
  "Setz dich auf einen anderen Platz",
  "Steh für 10 Sekunden",
  "Steh für 20 Sekunden",
  "Geh für 10 Sekunden langsam",
  "Geh für 10 Sekunden schnell",

  // Ruhig / Pause
  "Setz dich bequem hin",
  "Mach für 10 Sekunden nichts",
  "Mach für 20 Sekunden nichts",
  "Schau aus dem Fenster",
  "Schau an die Decke",
  "Schau auf den Boden",
  "Schließ kurz die Augen",
  "Atme einmal tief durch",
  "Atme dreimal ruhig durch",
  "Entspann deine Schultern",
  "Streck deine Arme",
  "Streck deine Beine",
  "Lehn dich zurück",
  "Mach eine kurze Pause",
  "Bleib einfach sitzen und warte 10 Sekunden",
  "Schau dich im Raum um",
  "Such dir einen gemütlichen Platz",
  "Mach es dir bequem",
  "Schau für 10 Sekunden niemanden an",
  "Bleib 15 Sekunden ruhig",

  // Kleine Raum-Aufgaben
  "Heb einen Gegenstand vom Boden auf",
  "Stell einen Gegenstand zurück",
  "Rück einen Gegenstand gerade",
  "Rück deinen Stuhl gerade",
  "Richte dein Kissen",
  "Richte deine Decke",
  "Heb 3 Dinge auf",
  "Heb 5 Dinge auf",
  "Mach einen kleinen Weg frei",
  "Stell etwas an seinen Platz",
  "Falte eine Decke",
  "Richte deinen Sitzplatz",
  "Stell einen Gegenstand aufrecht hin",
  "Bring einen Gegenstand an einen anderen Platz",
  "Suche etwas, das falsch herum liegt",
  "Dreh einen Gegenstand richtig herum",
  "Mach deinen Sitzplatz ordentlich",
  "Sammle 3 kleine Dinge ein",
  "Stell 2 Dinge nebeneinander",
  "Finde etwas, das nicht an seinem Platz liegt",

  // Zufällig
  "Wähle jemanden aus, der die nächste Aufgabe macht",
  "Bestimme die nächste Person",
  "Bestimme eine neue Regel für 1 Minute",
  "Alle stehen gleichzeitig auf",
  "Alle setzen sich gleichzeitig hin",
  "Alle klatschen gleichzeitig",
  "Alle machen eine Pose",
  "Alle sagen gleichzeitig ihren Namen",
  "Alle zeigen auf jemanden",
  "Alle drehen sich einmal",
  "Alle machen einen Hampelmann",
  "Alle machen 5 Kniebeugen",
  "Alle stehen auf einem Bein",
  "Alle machen 10 Sekunden lang eine Statue",
  "Alle machen ein Tiergeräusch",
  "Alle machen ein lustiges Gesicht",
  "Alle sagen eine Farbe",
  "Alle sagen ein Tier",
  "Alle sagen ein Essen",
  "Alle sagen einen Städtenamen",
  "Alle wechseln ihren Platz",
  "Alle zeigen auf etwas Rotes",
  "Alle zeigen auf etwas Rundes",
  "Alle zeigen auf etwas Blaues",
  "Alle suchen etwas Kleines",
  "Alle suchen etwas Weiches",
  "Alle suchen etwas Schwarzes",
  "Alle bleiben 10 Sekunden still",
  "Alle lachen absichtlich",
  "Alle machen gleichzeitig eine Siegerpose",
  "Alle machen gleichzeitig eine Roboterbewegung",
  "Alle gehen 5 Schritte",
  "Alle machen eine völlig zufällige Bewegung",
  "Alle denken sich eine neue Aufgabe aus",
  "Jeder nennt ein Tier",
  "Jeder nennt eine Farbe",
  "Jeder nennt ein Essen",
  "Jeder nennt ein Spiel",
  "Jeder nennt eine Stadt",
  "Jeder macht eine eigene Pose",
  "Jeder macht ein eigenes Geräusch",
  "Jeder zeigt auf einen Gegenstand",
  "Jeder sagt ein Wort",
  "Jeder macht eine Bewegung, die alle nachmachen",
  "Jeder nennt eine Superkraft",
  "Jeder nennt ein Lieblingstier",
  "Jeder nennt ein Lieblingsessen",
  "Jeder nennt einen Film",
  "Jeder nennt ein Spiel",

  // Noch mehr Quatsch
  "Tu so, als würdest du gerade einen Preis gewinnen",
  "Tu so, als würdest du im Fernsehen sein",
  "Tu so, als wärst du ein berühmter Schauspieler",
  "Tu so, als wärst du ein Fußballtrainer",
  "Tu so, als wärst du ein Verkäufer",
  "Tu so, als wärst du ein Lehrer",
  "Tu so, als wärst du ein Astronaut",
  "Tu so, als wärst du ein Pilot",
  "Tu so, als wärst du ein König",
  "Tu so, als wärst du ein Zauberer",
  "Tu so, als hättest du gerade im Lotto gewonnen",
  "Tu so, als hättest du gerade etwas Unglaubliches gesehen",
  "Tu so, als würdest du einen Film drehen",
  "Tu so, als würdest du eine Kochshow moderieren",
  "Tu so, als würdest du eine Nachrichtensendung moderieren",
  "Tu so, als würdest du einen Sport kommentieren",
  "Tu so, als würdest du einen Preis verleihen",
  "Tu so, als würdest du einen Alien treffen",
  "Tu so, als würdest du einen Geist sehen",
  "Tu so, als würdest du einen Dinosaurier sehen",
  "Mach 5 Sekunden lang eine Zeitlupenbewegung",
  "Mach 5 Sekunden lang eine Roboterbewegung",
  "Mach 5 Sekunden lang eine Tanzbewegung",
  "Mach 5 Sekunden lang eine Kampfpose",
  "Mach 5 Sekunden lang eine Superheldenpose",
  "Mach 5 Sekunden lang eine Statue",
  "Mach 5 Sekunden lang ein Tier nach",
  "Mach 5 Sekunden lang ein Fahrzeug nach",
  "Mach 5 Sekunden lang einen Roboter nach",
  "Mach 5 Sekunden lang einen NPC nach",
];